"""This file contains the AutogeneratedVesselList class,
which merely stores the parameters for an AutogeneratedVesselList

Classes:
    AutogeneratedVesselList
"""


class AutogeneratedVesselList:
    """This class stores the data for the summary.txt file.

    Attributes:
        nation_codes: list[str]
        always_include_years: list[int]
        loadout_include_years: list[int]
        always_include_vessels: list[str]
        never_include_vessels: list[str]

    Methods:
        None
    """

    def __init__(self, autogenerated_vessel_list_line: str) -> None:
        autogenerated_vessel_list_line.strip()
        try:
            self.nation_codes = autogenerated_vessel_list_line.split("|")[0].split(",")
            self.always_include_years = [
                int(year)
                for year in autogenerated_vessel_list_line.split("|")[1].split(",")
            ]
            self.loadout_include_years = [
                int(year) if year != "" else None
                for year in autogenerated_vessel_list_line.split("|")[2].split(",")
            ]
            self.always_include_vessels = autogenerated_vessel_list_line.split("|")[
                3
            ].split(",")
            self.never_include_vessels = autogenerated_vessel_list_line.split("|")[
                4
            ].split(",")
        except IndexError:
            pass
