"""This module contains the class for storing reports to be written to disk

Classes:
    Report
"""


class Report:
    """This class stores a singular report as generated by a tes

    Attributes:
        header: list[str] = [] Stores a header. Currently unused
        announcements: list[str] = [] | Stores announcments, which are displayed before everything else
        errors: list[str] = [] | Stores errors, problems which will prevent proper function
        warnings: list[str] = [] | Stores warnings, issues which may lead to undesireable behavior
        infos: list[str] = [] | Stores infos, remarks which may be overlooked but will not impede function

    Methods:
        None
    """

    def __init__(self):
        self.header = []
        self.announcements = []
        self.errors = []
        self.warnings = []
        self.infos = []
